[tool.pytest.ini_options]
asyncio_mode = "strict"

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
no_implicit_optional = false
warn_unused_ignores = false

[tool.ruff]
line-length = 120

