name: CI

on:
  pull_request:
    branches: [ main, feature/** ]
  push:
    branches: [ feature/** ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-asyncio ruff mypy prometheus-client
      - name: Lint (ruff)
        run: |
          ruff check . || true
      - name: Type check (mypy best-effort)
        run: |
          mypy --ignore-missing-imports --install-types --non-interactive . || true
      - name: Run unit tests
        run: |
          pytest -q || pytest -q
      - name: Run reliability tests
        run: |
          python test_reliability_improvements.py || true

  gates:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Evaluate metrics (placeholder)
        run: |
          echo "TODO: integrate metrics thresholds and gate PRs here"
          echo "PASS"

